language: python
python: 
    - 3.5
    - pypy3
compiler: gcc
matrix:
  include:
    - python: 3.6
      env:
      - TOX_ENV=py36
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
        - g++-4.9
        - pypy-dev
        - liblapack-dev
env:
 - TOX_ENV=py35
 - TOX_ENV=docs
 - TOX_ENV=flake8
 - TOX_ENV=pypy3
install:
 - |
        if [[ "${TRAVIS_PYTHON_VERSION}" = pypy3 ]]; then
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy-5.8.0
            pyenv global pypy-5.8.0
        fi
 - pip install tox
script:
 - tox -e $TOX_ENV
